import type {
  City,
  Place,
  Trip,
  DayPlan,
  DayStop,
  Neighborhood,
  User,
  TravelerPresence,
  Dish,
  SwapSuggestion,
  NearMeSuggestion,
  QuickAction,
} from "./types"

// ============ Cities ============
export const cities: City[] = [
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    description: "A dazzling blend of ultramodern and traditional, from neon-lit skyscrapers to historic temples.",
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "Japanese",
    highlights: ["Cherry blossoms", "Ramen culture", "Ancient temples", "Pop culture"],
    bestTimeToVisit: "March-May or September-November",
    neighborhoods: [
      {
        id: "shibuya",
        name: "Shibuya",
        description: "Youth culture hub with the famous scramble crossing",
        bestFor: ["Shopping", "Nightlife", "Photography"],
        vibes: ["Energetic", "Trendy", "Youthful"],
        priceLevel: 3,
      },
      {
        id: "shinjuku",
        name: "Shinjuku",
        description: "Entertainment district with towering skyscrapers and hidden bars",
        bestFor: ["Nightlife", "Food", "Entertainment"],
        vibes: ["Bustling", "Diverse", "Neon-lit"],
        priceLevel: 3,
      },
      {
        id: "asakusa",
        name: "Asakusa",
        description: "Traditional neighborhood home to Sensō-ji Temple",
        bestFor: ["Culture", "History", "Traditional food"],
        vibes: ["Historic", "Peaceful", "Authentic"],
        priceLevel: 2,
      },
      {
        id: "harajuku",
        name: "Harajuku",
        description: "Fashion-forward district with unique street style",
        bestFor: ["Fashion", "Cafes", "Photography"],
        vibes: ["Creative", "Quirky", "Colorful"],
        priceLevel: 2,
      },
      {
        id: "ginza",
        name: "Ginza",
        description: "Upscale shopping and fine dining district",
        bestFor: ["Luxury shopping", "Fine dining", "Art"],
        vibes: ["Elegant", "Sophisticated", "Upscale"],
        priceLevel: 4,
      },
    ],
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    description: "Japan's ancient capital, famous for classical Buddhist temples and traditional gardens.",
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "Japanese",
    highlights: ["Bamboo groves", "Geisha districts", "Tea ceremonies", "Traditional ryokans"],
    bestTimeToVisit: "March-May or October-November",
    neighborhoods: [],
  },
]

// ============ Places ============
export const places: Place[] = [
  {
    id: "meiji-shrine",
    name: "Meiji Jingu Shrine",
    description: "Peaceful shrine in a forested oasis",
    longDescription: "Serene Shinto shrine surrounded by tall trees. A spiritual start to the day, offering a peaceful escape from Tokyo's urban energy.",
    image: "https://images.unsplash.com/photo-1583766395091-2eb9994ed094?w=400&q=80",
    lat: 35.6764,
    lng: 139.6993,
    category: "temple",
    tags: ["Culture", "Nature", "Free", "Morning"],
    costLevel: 1,
    estimatedCost: 0,
    typicalDuration: 60,
    hiddenness: "balanced",
    popularityScore: 85,
    hiddenGemScore: 40,
    neighborhood: "Shibuya",
    address: "1-1 Yoyogikamizonocho, Shibuya City",
    openHours: {
      monday: "6:00 - 18:00",
      tuesday: "6:00 - 18:00",
      wednesday: "6:00 - 18:00",
      thursday: "6:00 - 18:00",
      friday: "6:00 - 18:00",
      saturday: "6:00 - 18:00",
      sunday: "6:00 - 18:00",
    },
    bestFor: ["Morning walks", "Photography", "Quiet reflection"],
    vibes: ["Peaceful", "Spiritual", "Natural"],
  },
  {
    id: "onibus-coffee",
    name: "ONIBUS Coffee Nakameguro",
    description: "Small-batch coffee in a cozy riverside spot",
    longDescription: "A specialty coffee shop by the Meguro River, known for carefully sourced beans and minimal aesthetic.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",
    lat: 35.6442,
    lng: 139.6989,
    category: "cafe",
    tags: ["Coffee", "Cozy", "Local favorite"],
    costLevel: 2,
    estimatedCost: 6,
    typicalDuration: 30,
    hiddenness: "hidden",
    popularityScore: 45,
    hiddenGemScore: 85,
    neighborhood: "Nakameguro",
    address: "2-14-1 Kamimeguro, Meguro City",
    bestFor: ["Coffee lovers", "Quiet mornings", "Work"],
    vibes: ["Minimal", "Calm", "Hip"],
    openHours: {
      monday: "9:00 - 18:00",
      tuesday: "9:00 - 18:00",
      wednesday: "9:00 - 18:00",
      thursday: "9:00 - 18:00",
      friday: "9:00 - 18:00",
      saturday: "8:00 - 19:00",
      sunday: "8:00 - 19:00",
    },
  },
  {
    id: "menya-musashi",
    name: "Menya Musashi Shinjuku",
    description: "Legendary ramen spot since 1996",
    longDescription: "One of Tokyo's most famous ramen shops, known for rich tonkotsu broth and perfectly chewy noodles.",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
    lat: 35.6896,
    lng: 139.7006,
    category: "restaurant",
    tags: ["Ramen", "Must-try", "Queue-worthy"],
    costLevel: 2,
    estimatedCost: 14,
    typicalDuration: 45,
    hiddenness: "touristy",
    popularityScore: 90,
    hiddenGemScore: 30,
    neighborhood: "Shinjuku",
    address: "3-35-7 Shinjuku, Shinjuku City",
    mustTryDishes: ["Tonkotsu Ramen", "Tsukemen"],
    bestFor: ["Lunch", "Ramen lovers"],
    vibes: ["Busy", "Authentic", "No-frills"],
  },
  {
    id: "21-21-design",
    name: "21_21 DESIGN SIGHT",
    description: "Design museum by Tadao Ando",
    longDescription: "A cutting-edge design museum housed in a striking building by architect Tadao Ando, featuring rotating exhibitions.",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=400&q=80",
    lat: 35.6655,
    lng: 139.7297,
    category: "museum",
    tags: ["Design", "Architecture", "Art"],
    costLevel: 2,
    estimatedCost: 6,
    typicalDuration: 90,
    hiddenness: "hidden",
    popularityScore: 55,
    hiddenGemScore: 80,
    neighborhood: "Roppongi",
    address: "9-7-6 Akasaka, Minato City",
    bestFor: ["Design enthusiasts", "Architecture lovers", "Rainy days"],
    vibes: ["Inspiring", "Modern", "Thoughtful"],
  },
  {
    id: "omoide-yokocho",
    name: "Omoide Yokocho",
    description: "Nostalgic alley with tiny yakitori stalls",
    longDescription: "A narrow alley of tiny bars and yakitori stalls, evoking post-war Tokyo atmosphere.",
    image: "https://images.unsplash.com/photo-1554797589-7241bb691973?w=400&q=80",
    lat: 35.6939,
    lng: 139.6984,
    category: "bar",
    tags: ["Nightlife", "Food", "Atmospheric"],
    costLevel: 2,
    estimatedCost: 18,
    typicalDuration: 90,
    hiddenness: "balanced",
    popularityScore: 75,
    hiddenGemScore: 55,
    neighborhood: "Shinjuku",
    address: "Nishishinjuku, Shinjuku City",
    mustTryDishes: ["Yakitori", "Hoppy"],
    bestFor: ["Evening drinks", "Street food", "Atmosphere"],
    vibes: ["Nostalgic", "Cramped", "Smoky"],
  },
  {
    id: "shinjuku-gyoen",
    name: "Shinjuku Gyoen National Garden",
    description: "Beautiful garden with seasonal blooms",
    longDescription: "One of Tokyo's largest and most beautiful gardens, featuring Japanese, French, and English landscape styles.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&q=80",
    lat: 35.6852,
    lng: 139.7100,
    category: "park",
    tags: ["Nature", "Cherry blossoms", "Peaceful"],
    costLevel: 1,
    estimatedCost: 5,
    typicalDuration: 120,
    hiddenness: "balanced",
    popularityScore: 80,
    hiddenGemScore: 45,
    neighborhood: "Shinjuku",
    address: "11 Naitomachi, Shinjuku City",
    bestFor: ["Relaxation", "Photography", "Picnics"],
    vibes: ["Serene", "Beautiful", "Spacious"],
  },
  {
    id: "teamlab-planets",
    name: "teamLab Planets",
    description: "Immersive digital art museum",
    longDescription: "A barefoot journey through water and immersive digital art installations.",
    image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=400&q=80",
    lat: 35.6425,
    lng: 139.7893,
    category: "museum",
    tags: ["Art", "Immersive", "Photography"],
    costLevel: 3,
    estimatedCost: 32,
    typicalDuration: 120,
    hiddenness: "touristy",
    popularityScore: 95,
    hiddenGemScore: 20,
    neighborhood: "Toyosu",
    address: "6-1-16 Toyosu, Koto City",
    bestFor: ["Art lovers", "Instagram", "Unique experiences"],
    vibes: ["Otherworldly", "Crowded", "Instagram-worthy"],
  },
  {
    id: "tsukiji-outer",
    name: "Tsukiji Outer Market",
    description: "Fresh seafood and street food paradise",
    longDescription: "The remaining outer market offers fresh sushi, tamagoyaki, and Japanese street food.",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&q=80",
    lat: 35.6654,
    lng: 139.7706,
    category: "market",
    tags: ["Food", "Seafood", "Street food"],
    costLevel: 2,
    estimatedCost: 25,
    typicalDuration: 90,
    hiddenness: "touristy",
    popularityScore: 88,
    hiddenGemScore: 35,
    neighborhood: "Tsukiji",
    address: "4 Chome Tsukiji, Chuo City",
    mustTryDishes: ["Sushi", "Tamagoyaki", "Fresh oysters"],
    bestFor: ["Breakfast", "Foodies", "Morning visits"],
    vibes: ["Busy", "Fresh", "Authentic"],
  },
  {
    id: "bakery-sasaki",
    name: "Bakery Sasaki",
    description: "Quieter spot with incredible shokupan",
    longDescription: "A local bakery known for its pillowy soft Japanese milk bread and pastries.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
    lat: 35.6450,
    lng: 139.7010,
    category: "cafe",
    tags: ["Bakery", "Local", "Breakfast"],
    costLevel: 1,
    estimatedCost: 4,
    typicalDuration: 20,
    hiddenness: "hidden",
    popularityScore: 25,
    hiddenGemScore: 92,
    neighborhood: "Nakameguro",
    address: "2-8-5 Kamimeguro, Meguro City",
    mustTryDishes: ["Shokupan", "Melon pan", "Anpan"],
    bestFor: ["Breakfast", "Quick bite", "Local experience"],
    vibes: ["Cozy", "Quiet", "Neighborhood"],
  },
  {
    id: "senso-ji",
    name: "Sensō-ji Temple",
    description: "Tokyo's oldest and most famous temple",
    longDescription: "Tokyo's oldest Buddhist temple, featuring the iconic Kaminarimon gate and Nakamise shopping street.",
    image: "https://images.unsplash.com/photo-1570521462033-3015e76e7432?w=400&q=80",
    lat: 35.7147,
    lng: 139.7966,
    category: "temple",
    tags: ["Culture", "History", "Free", "Photography"],
    costLevel: 1,
    estimatedCost: 0,
    typicalDuration: 60,
    hiddenness: "touristy",
    popularityScore: 95,
    hiddenGemScore: 15,
    neighborhood: "Asakusa",
    address: "2-3-1 Asakusa, Taito City",
    bestFor: ["First-timers", "Photography", "Cultural experience"],
    vibes: ["Historic", "Crowded", "Iconic"],
  },
  {
    id: "fuglen-tokyo",
    name: "Fuglen Tokyo",
    description: "Norwegian coffee and cocktail bar",
    longDescription: "By day a specialty coffee shop, by night a cocktail bar, featuring vintage Scandinavian furniture.",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&q=80",
    lat: 35.6651,
    lng: 139.6885,
    category: "cafe",
    tags: ["Coffee", "Cocktails", "Design"],
    costLevel: 2,
    estimatedCost: 8,
    typicalDuration: 45,
    hiddenness: "hidden",
    popularityScore: 50,
    hiddenGemScore: 78,
    neighborhood: "Tomigaya",
    address: "1-16-11 Tomigaya, Shibuya City",
    bestFor: ["Coffee snobs", "Evening drinks", "Design lovers"],
    vibes: ["Cool", "Intimate", "Scandinavian"],
  },
  {
    id: "golden-gai",
    name: "Golden Gai",
    description: "Labyrinth of tiny themed bars",
    longDescription: "A network of narrow alleys with over 200 tiny bars, each with unique themes and character.",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400&q=80",
    lat: 35.6946,
    lng: 139.7036,
    category: "bar",
    tags: ["Nightlife", "Unique", "Bars"],
    costLevel: 3,
    estimatedCost: 25,
    typicalDuration: 120,
    hiddenness: "balanced",
    popularityScore: 82,
    hiddenGemScore: 50,
    neighborhood: "Shinjuku",
    address: "1 Chome Kabukicho, Shinjuku City",
    bestFor: ["Bar hopping", "Night owls", "Unique experiences"],
    vibes: ["Eclectic", "Intimate", "Quirky"],
  },
]

// ============ Must-Try Dishes ============
export const tokyoDishes: Dish[] = [
  {
    id: "ramen",
    name: "Ramen",
    description: "Rich, savory noodle soup with various regional styles",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
    category: "lunch",
    cuisine: "Japanese",
    priceRange: "$10-15",
    bestPlaces: [places.find(p => p.id === "menya-musashi")!],
  },
  {
    id: "sushi",
    name: "Sushi",
    description: "Fresh, expertly prepared sushi at all price points",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&q=80",
    category: "dinner",
    cuisine: "Japanese",
    priceRange: "$15-100+",
    bestPlaces: [places.find(p => p.id === "tsukiji-outer")!],
  },
  {
    id: "yakitori",
    name: "Yakitori",
    description: "Grilled chicken skewers, perfect with beer",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
    category: "dinner",
    cuisine: "Japanese",
    priceRange: "$8-20",
    bestPlaces: [places.find(p => p.id === "omoide-yokocho")!],
  },
  {
    id: "matcha",
    name: "Matcha desserts",
    description: "Green tea flavored sweets and parfaits",
    image: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&q=80",
    category: "dessert",
    cuisine: "Japanese",
    priceRange: "$5-12",
    bestPlaces: [],
  },
]

// ============ Sample Users ============
export const sampleUsers: User[] = [
  {
    id: "user-1",
    name: "Avery",
    email: "avery@example.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    countryCode: "US",
    interests: ["food", "culture", "photography"],
    visibility: {
      showInCityLobby: true,
      showPlannedPlaces: true,
      allowMessages: true,
    },
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user-2",
    name: "Mika",
    email: "mika@example.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    countryCode: "DE",
    interests: ["art", "nightlife", "food"],
    visibility: {
      showInCityLobby: true,
      showPlannedPlaces: false,
      allowMessages: true,
    },
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "user-3",
    name: "James",
    email: "james@example.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    countryCode: "GB",
    interests: ["history", "culture", "nature"],
    visibility: {
      showInCityLobby: true,
      showPlannedPlaces: true,
      allowMessages: false,
    },
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "user-4",
    name: "Yuki",
    email: "yuki@example.com",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    countryCode: "JP",
    interests: ["food", "shopping", "nightlife"],
    visibility: {
      showInCityLobby: true,
      showPlannedPlaces: true,
      allowMessages: true,
    },
    createdAt: new Date("2024-03-25"),
  },
]

// ============ Travelers in Tokyo ============
export const tokyoTravelers: TravelerPresence[] = [
  {
    id: "presence-1",
    user: sampleUsers[1],
    cityId: "tokyo",
    dateRange: { start: "2025-05-17", end: "2025-05-24" },
    plannedPlaces: ["senso-ji", "teamlab-planets", "golden-gai"],
    intents: [
      {
        id: "intent-1",
        description: "Looking for someone to explore Golden Gai bars with on Friday night",
        category: "nightlife",
        date: "2025-05-19",
        maxGroupSize: 4,
        createdAt: new Date(),
      },
    ],
    visibility: "public",
  },
  {
    id: "presence-2",
    user: sampleUsers[2],
    cityId: "tokyo",
    dateRange: { start: "2025-05-18", end: "2025-05-22" },
    plannedPlaces: ["meiji-shrine", "shinjuku-gyoen"],
    intents: [
      {
        id: "intent-2",
        description: "Would love to find a local guide for temple visits",
        category: "activity",
        createdAt: new Date(),
      },
    ],
    visibility: "public",
  },
  {
    id: "presence-3",
    user: sampleUsers[3],
    cityId: "tokyo",
    dateRange: { start: "2025-05-16", end: "2025-05-25" },
    plannedPlaces: ["tsukiji-outer", "menya-musashi", "omoide-yokocho"],
    intents: [
      {
        id: "intent-3",
        description: "Street food crawl in Shibuya anyone?",
        category: "food",
        date: "2025-05-20",
        maxGroupSize: 6,
        createdAt: new Date(),
      },
    ],
    visibility: "public",
  },
]

// ============ Smart Swap Suggestions ============
export const swapSuggestions: SwapSuggestion[] = [
  {
    originalPlace: places.find(p => p.id === "onibus-coffee")!,
    suggestedPlace: places.find(p => p.id === "bakery-sasaki")!,
    reason: "cheaper",
    timeDifference: 3,
    costDifference: -2,
    distanceDifference: 0.2,
  },
  {
    originalPlace: places.find(p => p.id === "teamlab-planets")!,
    suggestedPlace: places.find(p => p.id === "21-21-design")!,
    reason: "more-local",
    timeDifference: -30,
    costDifference: -26,
    distanceDifference: -5,
  },
]

// ============ Quick Actions ============
export const quickActions: QuickAction[] = [
  {
    id: "fill-hour",
    label: "Fill 1 free hour",
    icon: "clock",
    filters: {
      maxDuration: 60,
      maxDistance: 1,
    },
  },
  {
    id: "rainy-day",
    label: "Rainy day ideas",
    icon: "cloud-rain",
    filters: {
      weather: "indoor",
      categories: ["museum", "cafe", "shopping"],
    },
  },
  {
    id: "late-night",
    label: "Late night spots",
    icon: "moon",
    filters: {
      timeOfDay: "night",
      categories: ["bar", "restaurant"],
    },
  },
  {
    id: "coffee-break",
    label: "Coffee nearby",
    icon: "coffee",
    filters: {
      maxDistance: 0.5,
      categories: ["cafe"],
    },
  },
  {
    id: "hidden-gems",
    label: "Hidden gems only",
    icon: "sparkles",
    filters: {},
  },
]

// ============ Near Me Suggestions ============
export const nearMeSuggestions: NearMeSuggestion[] = places.slice(0, 5).map((place, index) => ({
  place,
  distance: 0.3 + index * 0.4,
  matchScore: 95 - index * 8,
  reason: index === 0 ? "Perfect match for your interests" : index === 1 ? "Hidden gem nearby" : "Popular with travelers like you",
  estimatedArrival: `${5 + index * 3} min walk`,
  fitsTimeSlot: index < 3,
}))

// ============ Sample Trip ============
export const createSampleTrip = (): Trip => {
  const dayStops: DayStop[][] = [
    [
      {
        id: "stop-1-1",
        place: places.find(p => p.id === "meiji-shrine")!,
        startTime: "09:00",
        endTime: "10:00",
        order: 1,
        isBookmarked: false,
        travelFromPrevious: { distance: 0, duration: 0, mode: "walk" },
      },
      {
        id: "stop-1-2",
        place: places.find(p => p.id === "onibus-coffee")!,
        startTime: "11:00",
        endTime: "11:30",
        order: 2,
        isBookmarked: false,
        travelFromPrevious: { distance: 2.6, duration: 14, mode: "transit" },
      },
      {
        id: "stop-1-3",
        place: places.find(p => p.id === "menya-musashi")!,
        startTime: "13:00",
        endTime: "13:45",
        order: 3,
        isBookmarked: true,
        travelFromPrevious: { distance: 3.4, duration: 16, mode: "transit" },
      },
      {
        id: "stop-1-4",
        place: places.find(p => p.id === "21-21-design")!,
        startTime: "15:30",
        endTime: "17:00",
        order: 4,
        isBookmarked: false,
        travelFromPrevious: { distance: 1.1, duration: 12, mode: "walk" },
      },
      {
        id: "stop-1-5",
        place: places.find(p => p.id === "omoide-yokocho")!,
        startTime: "18:30",
        endTime: "20:00",
        order: 5,
        isBookmarked: false,
        travelFromPrevious: { distance: 0.3, duration: 6, mode: "walk" },
      },
    ],
    [
      {
        id: "stop-2-1",
        place: places.find(p => p.id === "shinjuku-gyoen")!,
        startTime: "08:30",
        endTime: "10:30",
        order: 1,
        isBookmarked: false,
        travelFromPrevious: { distance: 0, duration: 0, mode: "walk" },
      },
      {
        id: "stop-2-2",
        place: places.find(p => p.id === "teamlab-planets")!,
        startTime: "12:00",
        endTime: "14:00",
        order: 2,
        isBookmarked: true,
        travelFromPrevious: { distance: 8.5, duration: 35, mode: "transit" },
      },
      {
        id: "stop-2-3",
        place: places.find(p => p.id === "tsukiji-outer")!,
        startTime: "15:00",
        endTime: "16:30",
        order: 3,
        isBookmarked: false,
        travelFromPrevious: { distance: 2.1, duration: 15, mode: "transit" },
      },
      {
        id: "stop-2-4",
        place: places.find(p => p.id === "golden-gai")!,
        startTime: "19:00",
        endTime: "22:00",
        order: 4,
        isBookmarked: false,
        travelFromPrevious: { distance: 4.2, duration: 25, mode: "transit" },
      },
    ],
    [
      {
        id: "stop-3-1",
        place: places.find(p => p.id === "senso-ji")!,
        startTime: "07:00",
        endTime: "08:30",
        order: 1,
        isBookmarked: true,
        travelFromPrevious: { distance: 0, duration: 0, mode: "walk" },
      },
      {
        id: "stop-3-2",
        place: places.find(p => p.id === "fuglen-tokyo")!,
        startTime: "10:00",
        endTime: "11:00",
        order: 2,
        isBookmarked: false,
        travelFromPrevious: { distance: 5.8, duration: 28, mode: "transit" },
      },
    ],
  ]

  const days: DayPlan[] = [
    {
      id: "day-1",
      day: 1,
      date: "2025-05-18",
      stops: dayStops[0],
      estimatedCost: dayStops[0].reduce((sum, s) => sum + s.place.estimatedCost, 0),
    },
    {
      id: "day-2",
      day: 2,
      date: "2025-05-19",
      stops: dayStops[1],
      estimatedCost: dayStops[1].reduce((sum, s) => sum + s.place.estimatedCost, 0),
    },
    {
      id: "day-3",
      day: 3,
      date: "2025-05-20",
      stops: dayStops[2],
      estimatedCost: dayStops[2].reduce((sum, s) => sum + s.place.estimatedCost, 0),
    },
  ]

  return {
    id: "trip-tokyo-2025",
    destination: cities[0],
    startDate: "2025-05-18",
    endDate: "2025-05-22",
    partySize: 2,
    preferences: {
      budget: "mid",
      dailyBudget: 120,
      pace: "balanced",
      hiddenGemPreference: "mixed",
      interests: ["food", "culture", "art", "nature"],
    },
    days,
    collaborators: [
      {
        userId: "user-1",
        user: sampleUsers[0],
        role: "owner",
        invitedAt: new Date(),
      },
    ],
    isPublic: false,
    status: "planned",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
}

export const sampleTrip = createSampleTrip()
